"use server"
import { getServerSession } from "next-auth";
import db from "@/src/lib/prisma";
import { authOptions } from '../app/api/auth/[...nextauth]/options';
import { onboardingStatus } from "../types";
import { generateAIInsights } from "./dashboard";


export async function updateUser(data : any){
     const session = await getServerSession(authOptions);

       if (!session?.user?._id) {
         throw new Error("Unauthorized");
       
        }

 //mongodb user id from the session
  const authUserId = session.user._id;

  //look for this user id in the neon db
  const user=await db.user.findUnique({
    where:{
        authUserId 
    } ,
  });

   if(!user) throw new Error("User not found in neon db");

    
 //now we will make the connection with the database
   try{
    //since we are using three API's over here therefore we will use transaction of prisma
    const result = await db.$transaction(
  async(tx)=>{


    // FIRST API -> find if the industry exists

    let industryInsight = await tx.industryInsight.findUnique({
        where:{
            industry : "tech" ,
        } ,
    });


    // SECOND API -> if the industry does not exist then we will create it with default values and will replace it with AI later
    //edit: now the industry insights are being generated by the AI

    if(!industryInsight){
       //we will generate them using AI
          const insights = await generateAIInsights("Technology");
          industryInsight = await tx.industryInsight.upsert({
              where: { industry: "tech" },
                  update: {
              ...insights,
            },
            create: {
              industry: "tech",
              ...insights,
              nextUpdate:new Date(Date.now() +7*24*60*60*1000),
            },
          });
    }


    // Third API -> update the user
  const updatedUser = await tx.user.update({
    where:{
        id:user.id ,
    } ,
    data:{
        industry:"tech" ,
        experience : data.experience  ,
        bio: data.bio ,
        skills : data.skills ,
    } ,
  });

  return {updatedUser, industryInsight}
  } , 
  {
  timeout:30000 , //default :5000
  });

    return {
      success:true ,
      user:result.updatedUser ,
    }

   }catch(error){

console.log("Error updating user and industry:" , error);
throw new Error("Failed to update profile");

   }
}




export async function getUserOnboardingStatus(): Promise<onboardingStatus>{

   const session = await getServerSession(authOptions);

       if (!session?.user?._id) {

       throw new Error("Unauthorized access");
        }


 //mongodb user id from the session
  const authUserId = session.user._id;

   try{
    const user = await db.user.findUnique({
    where:{
        authUserId 
    } ,

    select:{
        industry:true ,
    } ,
      
   });

   if(!user){
    return {
      isOnboarded : false
    }
   }
    
   return {
    isOnboarded : !!user?.industry 
   };

}
catch(error){
    console.log("Error checking onboarding status" , error);
    return {
      isOnboarded : false
    }
}
}
